## PCA

-Reducing the number of independent variables 
-Transforms large set of variables into smaller ones
-PCA is an unsupervised technique. Only deals with independent variables

In [47]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
# Importing dataset
dataset = pd.read_csv("C:/Users/Mishaal/Desktop/wine.csv")
X = dataset.iloc[:, 1:13].values
Y = dataset.iloc[:, 0].values

In [28]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [49]:
# Split dataset into train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.20,
                                                    random_state=0)

In [50]:
#To apply PCA we need to do feature scaling
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [42]:
#We need to apply PCA before training machine learning model
# Apply PCA
from sklearn.decomposition import PCA 
pca = PCA(n_components=2) 
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_

In [44]:
X_train

array([[ 2.30317865,  0.72120942],
       [ 1.50125114, -1.74890507],
       [-1.68280433, -1.53807739],
       [ 2.78828739,  1.26175078],
       [-1.85009439,  0.03356869],
       [-2.07553555,  1.31871298],
       [-1.50394301, -1.52623299],
       [ 0.06227149, -2.4606764 ],
       [-0.17521639, -1.99866167],
       [-2.00252398,  1.4798327 ],
       [ 3.06337672, -0.41119091],
       [-2.03292557, -1.0645345 ],
       [ 2.41275753,  0.37142985],
       [-1.59577254,  2.27963348],
       [ 2.21411813, -0.00952229],
       [ 2.9981378 , -0.20119239],
       [-2.57454569,  1.41167475],
       [ 1.389568  ,  3.77713828],
       [-2.44502856,  0.09416406],
       [-0.79160824, -1.78176155],
       [ 3.08236363,  2.02792506],
       [ 2.73364551, -0.21252648],
       [-2.19501714,  0.07901316],
       [ 2.74892255,  0.15465634],
       [ 2.91575906,  1.74590938],
       [-0.92701029, -0.6637807 ],
       [ 2.2986043 , -0.2431242 ],
       [ 2.22490988, -1.00566457],
       [-1.70645604,

In [43]:
explained_variance

array([0.67239785, 0.32760215])

In [ ]:
pca.explained_variance_ratio_

In [33]:
# Fitting Logistic Regression to Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
classifier.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
# Predicting Test set results
Y_pred = classifier.predict(X_test)

In [45]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [46]:
cm

array([[13,  1,  0],
       [ 1, 15,  0],
       [ 0,  0,  6]], dtype=int64)

## Linear Discriminant Analysis (LDA)

-Reduce the dimentionality of Large datasets
-Supervised learning, deals with both dependent and independent variables 

In [51]:
# Linear Discriminant Analysis (LDA)
# Apply LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=2)
X_train = lda.fit_transform(X_train, Y_train) #supervised technique add both x_train,Y_train
X_test = lda.transform(X_test)
explained_variance = lda.explained_variance_ratio_

In [54]:
explained_variance

array([0.76606459, 0.23393541])

In [52]:
# Fitting Logistic Regression to Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
classifier.fit(X_train, Y_train)

# Predicting Test set results
Y_pred = classifier.predict(X_test)

# Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

In [53]:
cm

array([[14,  0,  0],
       [ 1, 15,  0],
       [ 0,  0,  6]], dtype=int64)